// <auto-generated />
using System;
using BlindDating.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlindDating.Migrations
{
    [DbContext(typeof(BlindDatingContext))]
    partial class BlindDatingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlindDating.Models.DatingProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<int?>("Age");

                    b.Property<string>("Bio")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("FirstName")
                        .HasColumnName("First_Name")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("LastName")
                        .HasColumnName("Last_Name")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("UserAccountId")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("DatingProfile");
                });

            modelBuilder.Entity("BlindDating.Models.Film", b =>
                {
                    b.Property<int>("Film_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<byte>("Language_id");

                    b.Property<DateTime>("Last_update");

                    b.Property<short?>("Length");

                    b.Property<byte?>("Original_language_id");

                    b.Property<string>("Rating");

                    b.Property<string>("Release_year");

                    b.Property<byte>("Rental_duration");

                    b.Property<decimal>("Rental_rate");

                    b.Property<decimal>("Replacement_cost");

                    b.Property<string>("Special_features");

                    b.Property<string>("Title");

                    b.HasKey("Film_id");

                    b.ToTable("Film");
                });
#pragma warning restore 612, 618
        }
    }
}
